### ISSUE TITLE
v0.2.1 Connection issues

### ISSUE THREAD

**Issue by mjgorman** [tujson/GlassEcho#15]
Hello, 

I just sideloaded the apk on to my XE24 running Glass. That seems to work, when starting it i get the QR scanner. 

On the phone I granted restricted access to read notifications on first run and all others it asked for on pressing connect. It when shows the QR code but only for a milisecond before popping up a bluetooth permission to enable discoverable for 300 seconds. I can hit allow, but then echo doesn't re-open, and re-opening it starts me back from square one. 

Phone is a Pixel 7.

**Comment by xiongnemo** [comment]
Me too:

![Screenshot_2023-12-23-13-29-12-658_com miui bugreport](https://github.com/tujson/GlassEcho/assets/38759782/877a38bb-88b2-49c7-a324-960ad6ee0ee4)

but I currently have no time to dig into it :|

**Comment by tujson** [comment]
Thanks for the bug report! Should be fixed.
https://github.com/tujson/GlassEcho/commit/f0bef4722f5af407d8a42157103d7ddc9be36786
