### ISSUE TITLE
The lastest update is not working for my glass

### ISSUE THREAD

**Issue by ennis-ma** [tujson/GlassEcho#2]
I followed the instruction and successfully connected my glass to phone via QRcode. I do get a notification on my phone saying "Echoing notification to Glass", but on the glass it seems the app was crashed right after the connection.

Anyways thank you so much for still developing for the glass.

**Comment by tujson** [comment]
Hi!
Yeah, Glass accidentally said it was connected when in fact the phone didn't even start accepting connections.
The latest update should fix things, but it does have some extra code concerning auto-reconnection (which is still shaky on stability).
